version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/postgres
    ports:
      - 5432:5432
    restart: unless-stopped

  api:
    container_name: api-container
    image: node:16.13.0
    working_dir: /usr/src
    restart: always
    command: bash -c "yarn && yarn dev"
    volumes:
      - ./:/usr/src
    ports:
      - 3333:3333
    links:
      - postgres
